### ISSUE TITLE
Example with Immutable.js?

### ISSUE THREAD

**Issue by stunaz** [raquo/facebook-flow-examples#1]
Hi, it would be nice if you can provide examples with [immutable-js](https://facebook.github.io/immutable-js/) usage of `Map`, `List`, `Record` ...

**Comment by raquo** [comment]
Hi, unfortunately I haven't found a good way to deal with Immutable.js in pure Flow. That library is very dynamically typed, making it next to impossible to strongly type. All the typings I've seen are way too loose, making liberal use of `any` type.

I think [stephanos/babel-plugin-immutable-record](https://github.com/stephanos/babel-plugin-immutable-record) is the most promising approach. Basically, you precompile type definitions specific to your particular classes. I've tried it but ran out of time I've allotted myself on this.

I personally turned my attention to [Scala.js](https://www.scala-js.org/) which offers a robust type system that is unbound from Javascript semantics. It has immutable datatypes built into the language itself.
